name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # python -m pip install -r "openalex-data-miner/requirements.txt"
        
    - name: Run Python script
      run: |
        # for d in $(find . -type d -name ".git"); do
        #   module_dir=$(dirname "$d")
        #   echo $module_dir
        #   if [ -f "$module_dir/requirements.txt" ]; then
        #     python -m pip install -r "$module_dir/requirements.txt"
        #     python test.py
        #   fi
        # done
        python test.py
